[project]
name = "server"
version = "0.1.0"
description = ""
authors = [
    {name = "Naomie",email = "107333@ecole-it.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (>=5.2.1,<6.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
<<<<<<< HEAD
    "django-cors-headers (>=4.7.0,<5.0.0)",
    "djangorestframework (>=3.16.0,<4.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)"
=======
    "djangorestframework (>=3.16.0,<4.0.0)"
>>>>>>> 2d745a1e8f33b2c34cee133cf19703eb645dae22
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
