name: CD - Deploy with Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            cd /chemin/vers/ton/projet

            echo "[1] Pull latest code..."
            git pull origin main

            echo "[2] Pull latest env secrets if needed (e.g. from S3 or vault)..."

            echo "[3] Build and deploy with Docker Compose..."
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d --remove-orphans
          EOF
