name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_DB_HOST: localhost
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DEBUG: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run:

      - name: Run Django tests
        run: |
          python manage.py migrate
          python manage.py test
