name: CI - Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker containers
        run: docker-compose up -d --build

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec $(docker ps -qf "name=db") pg_isready -U postgres; do
            echo "Retrying..."
            sleep 2
          done

      - name: Run migrations
        run: docker-compose exec -T web python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec -T web python manage.py test

      - name: Stop containers
        run: docker-compose down -v

