name: CI - Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker containers
        run: docker-compose up -d --build

      - name: Wait for database to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          docker-compose exec -T web sh -c 'while ! nc -z db 5432; do sleep 1; done'

      - name: Run Django tests
        run: docker-compose exec -T web python manage.py test

      - name: Tear down containers
        run: docker-compose down -v
