name: CI/CD - Django & React

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Test Django (Poetry)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_DB_HOST: localhost
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          cd server
          poetry install

      - name: Run migrations and tests
        run: |
          cd server
          poetry run python manage.py migrate
          poetry run python manage.py test

  frontend:
    name: uild React (Yarn)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend
        run: |
          cd client
          yarn install
          yarn build

